language: node_js
node_js:
  - "8"

os:
  - windows
  - linux
  - osx

env:
  - CODECOV_TOKEN=9048c8f4-2f20-4ece-bf04-a4065ca75a17
  - NPM_TOKEN=a4378046-22b6-4a0f-8629-bc9ed4f869fc

before_script:
  - npm run build

script:
  - nyc --reporter=lcov --reporter=html node build/testy.js
  - nyc --reporter=text-lcov > coverage.lcov
  - codecov
  - npm run lint
