name: Publish

on:
  push:
    tags:
      - testy-cli/v**.**.**

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [8.x, 10.x, 12.x, 14.x, 15.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        working-directory: packages/testy-cli
        run: npm ci
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Build
        working-directory: packages/testy-cli
        run: npm run build --if-present
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Run unit tests
        working-directory: packages/testy-cli
        run: npm test
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}

  e2e-tests:
    name: E2E tests
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: [8.x, 10.x, 12.x, 14.x, 15.x]
        os: [macos-latest, ubuntu-latest, windows-latest]
        include:
          - os: macos-latest
          - os: windows-latest
          - os: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Build
        working-directory: packages/testy-cli
        run: npm ci

        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Run e2e tests
        working-directory: packages/testy-cli
        run: node ./e2e/runner.js
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}

  publish:
    name: Publish to npm
    needs: [unit-tests, e2e-tests]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install dependencies
        working-directory: packages/testy-cli
        run: npm ci
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Build
        working-directory: packages/testy-cli
        run: npm run build:prod --if-present
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Extract tag
        working-directory: packages/testy-cli
        uses: olegtarasov/get-tag@v2.1
        id: tagName
        with:
          tagRegex: "v[0-9]+.[0-9]+.[0-9]+-([^\\.]+)"

      - name: Publish (${{ steps.tagName.outputs.tag }})
        if: ${{ steps.tagName.outputs.tag != ''}}
        working-directory: packages/testy-cli
        run: npm publish --access public --tag ${{ steps.tagName.outputs.tag }}
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Publish (latest)
        if: ${{ steps.tagName.outputs.tag == ''}}
        working-directory: packages/testy-cli
        run: npm publish --access public
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
