name: Publish

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    
    - name: npm install, build, and test
      run: |
        npm ci
        npm run build --if-present
        npm test
        npm publish --access public
      env:
        NPM_TOKEN: ${{secrets.NPM_TOKEN}}
        CI: true
